#Warning: This file can contain server names, passwords, email addresses and other sensitive information.
#Wed Aug 19 22:43:07 GMT+08:00 2026
log_customurl_basicauth_username=
last_version_seen=137
log_geojson=false
only_log_if_significant_motion=false
osm_tags=
autosend_frequency_minutes=60
httpfileupload_url=
passive_filter_interval=60
owncloud_directory=/gpslogger
user_specified_locale=
retry_time=5
dawarich_discard_offline_logs=false
absolute_timeout=5
owncloud_server=
owncloud_username=
osm_visibility=trackable
log_customurl_headers=
autoftp_implicit=false
httpfileupload_method=POST
useImperial=false
autoopengts_enabled=false
dawarich_bulk_max=10
log_plain_text_csv_delimiter=,
log_customurl_method=GET
opengts_server=
distance_before_logging=0
opengts_server_communication_method=HTTPS
autoftp_ssltls=
owncloud_enabled=false
app_theme_setting=system
autoopengts_server_path=
smtp_username=
dawarich_bulk_min=3
dawarich_apikey=
autoftp_password=
smtp_password=
hide_notification_buttons=false
log_gpx=true
autoftp_server=
opengts_server_port=443
altitude_subtractoffset=0
dropbox_enabled=false
log_customurl_basicauth_hide_password=false
latlong_display_format=DEGREES_MINUTES_SECONDS
dawarich_persistence_file_path=
autoftp_useftps=false
hide_notification_from_status_bar=false
autohttpfileupload_enabled=false
autosend_enabled=false
new_file_custom_each_time=true
osm_description=
hide_notification_from_lock_screen=true
autoemail_enabled=false
log_opengts=false
stoponapplaunch=false
httpfileupload_basicauth_password=
log_network_locations=true
autoftp_enabled=false
google_drive_enabled=false
log_satellite_locations=true
autoftp_port=21
google_drive_folder_path=GPSLogger for Android
log_customurl_basicauth_password=
current_profile_name=Default Profile
log_customurl_url=http\://localhost/log?lat\=%LAT&longitude\=%LON&time\=%TIME&s\=%SPD
log_customurl_discard_offline_locations_enabled=false
owncloud_password=
new_file_creation=onceaday
log_kml=false
significant_motion_bypass_interval=0
autosend_frequency_whenstoppressed=true
accuracy_before_logging=200
log_nmea=false
smtp_port=25
opengts_accountname=
smtp_server=
autoftp_username=
log_customurl_body=
altitude_subtractgeoidheight=false
autoftp_directory=GPSLogger
log_plain_text=false
autosend_wifionly=false
new_file_prefix_serial=false
log_plain_text_csv_decimal_comma=false
opengts_device_id=
dawarich_server=
osm_promptfordetails_when_logging_starts=true
httpfileupload_body_type=form-data
autosend_sendzip=true
gpslogger_folder=/storage/emulated/0/Documents/GPSLogger
smtp_ssl=true
dawarich_enable_logging=false
time_before_logging=60
startonbootup=true
log_gpx_11=false
log_customurl_enabled=false
dawarich_device_id=
osm_enabled=false
startonapplaunch=false
new_file_custom_name=gpslogger
autoemail_target=
log_passive_locations=true
retry_get_best_possible_accuracy=false
httpfileupload_basicauth_username=
annotations_buttons=
httpfileupload_headers=
keep_fix=false
new_file_custom_keep_changing=true
