gh repo clone tmp
gh repo clone Android-Non-Root
gh repo clone AutoJs6-scripts
gh repo clone bashrc
gh repo clone LICENSES
gh repo clone LaTeX-ToolKit
gh repo clone LinuxAndTermuxTips
gh repo clone MarkdownToLatexConverter
gh repo clone Samsung-Android-Debloat-List
gh repo clone Willie169
gh repo clone Willie169.github.io
gh repo clone add-search-engines
gh repo clone dual-boot-windows-linux-and-recovery
gh repo clone format-converter
gh repo clone homebrew-tap
gh repo clone metasploit_in_termux
gh repo clone physics-patch
gh repo clone switch-firefox-from-snap-to-deb
gh repo clone termux-sh
gh repo clone ubuntu-setup-with-vnc-and-gpu
gh repo clone vimrc
gh repo clone willie169-ckhs-ntuee-notes
